services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upv-contacts
    ports:
      - "8080:8080"
    volumes:
      - cache:/usr/src/app/cache

volumes:
  cache:
